[versions]
kotlin = "2.0.0"
gradle = "8.2.2"
dependencyVersionsPlugin = "0.51.0"
nexusSonatype = "2.0.0"
dokka = "1.9.20"
androidAnnotations = "1.8.0"
coroutines = "1.8.1"
napier = "2.7.1"
kotlinxDatetime = "0.6.0"
realm = "2.0.0"
serializationJson = "1.6.3"
firebaseGitLiveApp = "1.12.0" # Firebase for KMP https://firebaseopensource.com/projects/gitliveapp/firebase-kotlin-sdk/
bomGeneratorPlugin = "1.0.0.Final"

# Tweener
tweenerCharts = "1.1.0"

# Android
androidDesugarJdkLibs = "2.0.4"
androidCore = "1.13.1"

[libraries]
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
realm = { group = "io.realm.kotlin", name = "library-base", version.ref = "realm" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# Tweener
tweener-charts = { group = "io.github.tweener", name = "kmp-charts", version.ref = "tweenerCharts" }

# Coroutines
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Firebase GitLive
firebase-firestore = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "firebaseGitLiveApp" }
firebase-config = { group = "dev.gitlive", name = "firebase-config", version.ref = "firebaseGitLiveApp" }
firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebaseGitLiveApp" }
firebase-functions = { group = "dev.gitlive", name = "firebase-functions", version.ref = "firebaseGitLiveApp" }
firebase-crashlytics = { group = "dev.gitlive", name = "firebase-crashlytics", version.ref = "firebaseGitLiveApp" }

# Android
android-desugarjdklibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
android-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "androidAnnotations" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
dependency-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersionsPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-sonatype = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusSonatype" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
bom-generator = { id = "io.github.gradlebom.generator-plugin", version.ref = "bomGeneratorPlugin" }
